# Funding for AstraLumen

# LFX Mentorship (formerly CommunityBridge)
community_bridge: 

# GitHub Sponsors
github: [idugeni, rutanwonosobo, sayaptawon]

# IssueHunt
issuehunt: 

# Ko-fi
ko_fi: eliyantosarage

# Liberapay
liberapay: 

# Open Collective
open_collective: 

# Patreon
patreon: 

# Tidelift
tidelift: 

# Polar
polar: 

# Buy Me a Coffee
buy_me_a_coffee: eliyantosarage

# thanks.dev
thanks_dev: u/gh/idugeni

# Custom URLs
custom: []